# Configuration
server:
  servlet:
    context-path:
  port: 8070
# datasource
spring:
  datasource:
    username: root
    url: jdbc:mysql://database-1.cw7lwywc9t1a.ap-southeast-2.rds.amazonaws.com/property_sale?serverTimezone=Australia/Sydney&&useUnicode=true&characterEncoding=UTF-8&&useSSL=true
    password: znx5201314
    driver-class-name: com.mysql.cj.jdbc.Driver
# redis
  redis:
    password: 123456
    host: 3.24.78.45
    timeout: 5000

  # mail
  mail:
    host: smtp.gmail.com
    default-encoding: utf-8
    username: zxhhaha@gmail.com
    password: znx5201314
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            required: true
          timeout: 10000
          connectiontimeout: 10000
          writetimeout: 10000
          port: 465
  # rabbitmq
  rabbitmq:
    host: 3.24.78.45
    username: admin
    password: admin
    myExchange: alpha.go.sender
  servlet:
    multipart:
      max-file-size: 10MB

# mybatis plus
mybatis-plus:
  mapper-locations:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true

# Cloud Server Address
remote:
  url: http://3.24.78.45:8060/img/

