server:
  servlet:
    context-path:
  port: 8070
# datasource
spring:
  datasource:
    username: root
    password: znx5201314
    url: jdbc:mysql://13.238.115.166:3306/property_sale?serverTimezone=UTC&&useUnicode=true&characterEncoding=UTF-8&&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
# redis
  redis:
    password: 123456
    host: 13.238.115.166
    timeout: 5000

  # mail
  mail:
    host: smtp.gmail.com
    default-encoding: utf-8
    username: zxhhaha@gmail.com
    password: znx5201314
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            required: true
          # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connectiontimeout: 10000
          # 邮件发送时间的限制，单位毫秒
          writetimeout: 10000
          port: 465
  # rabbitmq
  rabbitmq:
    host: 13.238.115.166
    username: admin
    password: admin
    myExchange: alpha.go.sender
  servlet:
    multipart:
      max-file-size: 10MB

# mybatis plus
mybatis-plus:
  mapper-locations:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true


remote:
  url: http://localhost:8060/img/

